general_parameters = \
    {'System': '\'MULHACEN\'',
     'Laser_Pointing_Angle': 0,
     'Molecular_Calc': 0,
     'Latitude_degrees_north': 37.164,
     'Longitude_degrees_east': -3.605,
     'Altitude_meter_asl': 680.0,
     'Call sign': "gr"}

channel_parameters = \
    {'BT2': {'channel_ID': 1049,
                    'channel_str_ID': 'gr_0355xta',
                    'Background_Low': 75000,
                    'Background_High': 105000,
                    'Laser_Shots': 600,
                    'LR_Input': 1,
                    'DAQ_Range': 500.0, },
     'BC2': {'channel_ID': 1090,
                    'channel_str_ID': 'gr_0355xtp',
                    'Background_Low': 75000,
                    'Background_High': 105000,
                    'Laser_Shots': 600,
                    'LR_Input': 1,
                    'DAQ_Range': 0, },
     'BC4': {'channel_ID': 1047,
                    'channel_str_ID': 'gr_0353xtp',
                    'Background_Low': 75000,
                    'Background_High': 105000,
                    'Laser_Shots': 600,
                    'LR_Input': 1,
                    'DAQ_Range': 0, },
     }
