general_parameters = \
    {'System': '\'MULHACEN\'',
     'Laser_Pointing_Angle': 0,
     'Molecular_Calc': 0,
     'Latitude_degrees_north': 37.164,
     'Longitude_degrees_east': -3.605,
     'Altitude_meter_asl': 680.0,
     'Call sign': "gr"}

channel_parameters = \
    {'BT0': {'channel_ID': 1091,
                    'channel_str_ID': 'gr_0532xpa',
                    'Background_Low': 75000,
                    'Background_High': 105000,
                    'Laser_Shots': 600,
                    'LR_Input': 1,
                    'DAQ_Range': 500.0, },
     'BC0': {'channel_ID': 1094,
                    'channel_str_ID': 'gr_0532xpp',
                    'Background_Low': 75000,
                    'Background_High': 105000,
                    'Laser_Shots': 600,
                    'LR_Input': 1,
                    'DAQ_Range': 0, },
     'BT1': {'channel_ID': 1092,
                    'channel_str_ID': 'gr_0532xca',
                    'Background_Low': 75000,
                    'Background_High': 105000,
                    'Laser_Shots': 600,
                    'LR_Input': 1,
                    'DAQ_Range': 500.0, },
     'BC1': {'channel_ID': 1093,
                    'channel_str_ID': 'gr_0532xcp',
                    'Background_Low': 75000,
                    'Background_High': 105000,
                    'Laser_Shots': 600,
                    'LR_Input': 1,
                    'DAQ_Range': 0, },
     }
